services:
  - type: web
    name: level-gastrobar-pos-remote
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_TOKEN
        value: level-secret-token-2026
      - key: ADMIN_PIN
        value: 1234
